woocommerce/woocommerce-google-analytics-integration

includes/class-wc-google-analytics.php
As part of cleaning up the Analytics plugin, I wanted to fix up some of the settings language to make it clear when and why to enable something. I also wanted to separate out the "what to track" options from the other settings since we will be adding more as part of enhanced eCommerce (#17).
I also added a few notes around requirements. Mainly that tracking transactions requires a gateway that redirects to order received (all default gateways), and how to upgrade to universal analytics.
=> Clean up setting language and provide some more helpful information

includes/class-wc-google-analytics-info-banner.php, includes/class-wc-google-analytics.php
I mentioned this idea to @claudiosmweb the other day, but displaying some additional information (that may have been missed in the readme) would help users understand some of the requirements of the plugin and might reduce some of the initial "it's broken"/"my analytics are not showing" support requests. Think of it as a super simple onboarding message :).
The notice can be permanently dismissed by the user, only displays on WooCommerce settings pages, and will also disappear when the GA ID is set (so it should not show for upgraded users unless they have never configured GA before).
Here is what it looks like:
=> Display a helpful banner after installing the analytics plugin

includes/class-wc-google-analytics.php
This PR tracks the enabled/disabled status for the Google Analytics options. Closes #10. cc @kloon. 
We can also track the enhanced options in that PR after this one lands, since it's smaller.
=> Track settings for the google analytics plugin

includes/class-wc-google-analytics-js.php, includes/class-wc-google-analytics.php
Closes #17.
This PR adds GA's enhanced ecommerce functionality to the plugin. By default, it is off and requires flipping a setting under the integration tab (you also have to configure something on the GA side). Once it is turned on, it tracks removing a product from a cart, product impressions, product clicks, product detail views, checkout, adding to a cart, and transactions giving a full view of the entire ecommerce flow. Each of these can also be flipped off depending on what you want to track.
=> Add Enhanced Ecommerce Capabilities

readme.txt, woocommerce-google-analytics-integration.php
Since 1.4 has a lot of changes and is a refactor, we want to run a beta. Bumping some info before tagging a release.
=> Bump info to 1.4.0-beta-1

includes/class-wc-google-analytics-js.php, includes/class-wc-google-analytics.php, readme.txt
Fixes #54.
This PR allows the `ga` variable to be filtered which can be useful if there are multiple trackers on the same page. By default `ga` is used.
=> Allow the tracker filter to be changeable

includes/class-wc-google-analytics.php
The tracking code is being run twice on the checkout page - if the code is already loaded, then we shouldn't bother showing the checkout code again.
=> Make sure the tracking code is not loaded twice on the checkout page

includes/class-wc-google-analytics.php
This PR fixes a minor PHP notice shown when loading a settings page without a 'tab' query arg.
PHP Notice:  Undefined index: tab in includes/class-wc-google-analytics.php
=> Fix a PHP Notice

includes/class-wc-google-analytics-info-banner.php
The "Connect WooCommerce to Google Analytics" link just sends you to the main WooCommerce integration page. We should be sending them to the correct tab as well, just in case there are multiple integrations configured.
No changelog is needed since this bit is new in 1.4 and is unreleased.
=> Correctly link to the GA setup from the info banner

readme.txt
The formatting on https://wordpress.org/plugins/woocommerce-google-analytics-integration/changelog/ isn't quite correct.
Also adds an upgrade notice in order to encourage people to upgrade.
=> v1.4.0 Readme changelog fix

includes/class-wc-google-analytics-js.php
It would be helpful to pass separate portions of the snippet output through filters so developers can more easily integrate any site specific analytics tracking with the plugin. Examples where this would be useful include:
* Requiring custom GA plugins
* https://developers.google.com/analytics/devguides/collection/analyticsjs/using-plugins
* Modifying the create value for Cross Domain Tracking
* https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain?hl=en
* Creating custom cookie domains and user tracking
* https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id?hl=en
I'm agnostic on applying a filter to what I've labeled as "ga_snippet_head", but "ga_snippet_create" and "ga_snippet_require" would be of great use for building …
=> Add filters to the Universal snippet output

includes/class-wc-google-analytics-js.php
Without this fix, it will generate errors when position is null.
Fixes #74.
=> Added string escape for position

includes/class-wc-google-analytics-js.php
Fixes #84 and #93.
- Fixes #84 Undefined variable: ga_id
- Fixes #93 Missing Google Analytics ID #93
=> Fixes #84 Undefined variable: ga_id and #93 Missing Google Analytics ID 

includes/class-wc-google-analytics.php
This adds a simple filter to the `disable_tracking` method and then removes some duplicate code in the `tracking_code_display` method to make it work. Feedback is welcome.
Fixes #108.
- Add a filter so other plugins can disable analytics tracking on demand
=> Add filter to optionally disable all tracking

includes/class-wc-google-analytics.php
Fixes #124.
If we have an invalid order ID, we wind up throwing a fatal PHP error. This seems to solve the problem.
- Use `wc_get_order()` instead of `new WC_Order()`
- Validate the order object before we try to use it.
=> Fix fatal error on Thank You page

changelog.txt, includes/class-wc-google-analytics-js.php, readme.txt
Fixes #119
* Fix - Event for deleting from cart not sent after a cart update.
=> Fix delete item event not sent after a cart update fixes #119

includes/class-wc-google-analytics-js.php
=> Ensure universal analytics pageview doesn’t occur if standard tracking is disabled

includes/class-wc-google-analytics-js.php
This way other plugins can override the source, for example by a local copy (e.g. provided by CAOS for Analytics).
- I've been getting many requests for this on the WP Support Forums and by e-mail. So I decided to make a pull request. Adding a filter the the analytics.js source URL will make it easy for plugins to alter the source of the analytics.js file. Some people want to host it locally, to up their Pagespeed score. My plugin does that, and keeps it updated using wp-cron. If you'd implement this, I could create an option to make my plugin compatible with yours! :)
=> Make analytics.js src filterable

changelog.txt, includes/class-wc-google-analytics-js.php
Fixes #149
Issue introduced in #140
- Adds missing quotes and comma
1. Set tracking ID and enable universal analytics
2. Log out of admin account
3. Go to tracked pages (e.g. cart page), make sure no errors exist:
4. Make sure analytics.js is loading:
=> Add missing quotes for script source.

package.json
Splits out the build into two separate steps:
1. Build for release
- Includes only non dev dependencies in composer
- Creates a zip archive
2. Build for development
- Includes all dependencies in composer (including dev)
- Generates all resources, but does not create a zip archive
Note: For extensions that don't have any composer dependencies we don't run composer install at all so the autoloader isn't included.
Closes https://github.com/woocommerce/woocommerce-extension-library/issues/130
1. Run `npm install && npm run build`
2. Confirm that the zip archive is created and doesn't contain any dev dependencies (most our extensions won't have any)
=> Add dev build script

changelog.txt, includes/class-wc-google-analytics-js.php
When the order-received page is loaded the first time the metadata `_ga_tracked` is saved on the order to prevent it from being tracked twice. However as we can see in the original issue there are scenarios where the page is not reloaded a second time from the server. For example if there is caching in place, or cases where the page is later reopened on a mobile device where the page is reloaded without requesting it from the server.
Thanks to @tc33 for the original PR: https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/165
In this PR it was suggested to use localStorage to save the order ID's, which can be checked before sending the request. The solution from the original PR was copied and modified slightly to fallback in scenarios where localStorage is not …
=> Check localStorage to avoid duplicate transactions
